server:
  port: 8001
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/monkeyshop?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    cache: false
    prefix: classpath:/static/
    suffix: .html
    encoding: utf-8
    mode: HTML5
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 200MB
#  mvc:
#    static-path-pattern: classpath:/static/**
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
